defaults:
  - model@train.model: rnn

mode:
- EProgramMode.Train
train:
  gpu: true
  dataset_filename: data/processed/spam.csv
  vectors_cache_directory: .vector_cache
  test_size: 0.25
  tokenizer_name: basic_english
  epochs: 100
  batch_size: 64
  loss_fn: EBCEWithLogitsLoss
  optimizer: SGD
  learning_rate: 0.1
  dump_model: models/model.dmp
  lr_scheduler:
    type: 'No'
    step_size: 10
    gamma: 0.5
  interactive: false
  report_path: reports/train_report.csv
prepare_data:
  input_file: data/raw/spam.csv