# @package _group_
model_args:
  pretrained_vectors: glove.6B.100d
  input_size: 100
  hidden_size: 200
  num_layers: 2
  dropout: 0
  bidirectional: false
  num_classes: 1
  min_sequence_to_loss: 8
model_type: RNN
one_batch_runner: Rnn